# Generated by Django 3.2.6 on 2021-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["id"]},
        ),
    ]
