# Generated by Django 3.2.6 on 2021-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["id"]},
        ),
    ]
